# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9872f4ec6ecefed9e88976937b0a15202ee1c768df733b73f111d97d4a9d5dc0f45ad1604035559619124e21ed52c0039e8f4302e9ac979aa2744d47164717a3

test:
  secret_key_base: b3375c727c4193c00d326fea1658fc0e82a1d3fc7d3e90058ba7c5fb07ffb2f9291c660e9ac5159699f5a53b1ab3fde335eed947330593124e25a217d075f307

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
